# Generated by Django 4.2.22 on 2025-06-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatement_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='patien_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('breed', models.CharField(max_length=225)),
                ('date', models.DateTimeField()),
                ('doctor', models.CharField(default='hp', max_length=225)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.treatement_category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patien_log',
            constraint=models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_appointment_time'),
        ),
    ]
