# Generated by Django 4.2.22 on 2025-06-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_type_alter_patien_log_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patien_log',
            new_name='patient_log',
        ),
    ]
